class MoveDataFrame():

    def __init__(self):
        #....
    
    def head():
        #....
    
    def show_trajectories_info(self):
        #....
    
    def read_file():
        #....

    def write_file(self):
        #....
    
    def plot_all_features():
        #....
    
    def plot_trajs(self):
        #....
    
    def plot_traj_id():
        #....
    
    def len():
        #....
    
    def get_user_number(self):
        #....
    
    def time_interval():
        #....
    
    def get_bbox():
        #....
    
    def __getattr__(self):
        #....

    def __setattr__(self):
        #....

    def to_csv():
        #...

    def to_numpy():
        #...  

    def to_dict():
        #...  

    def to_grid():
        #...

    def with_tid_based_on_id_datatime():
        #...    

    def with_date_features():
        #...
    
    def with_hour_features():
        #...

    def with_day_of_the_week_features():
        #...

    def with_time_of_day_features():
        #...

    def with_dist_features():
        #...
    
    def with_dist_time_speed_features():
        #...

    def with_move_and_stop_by_radius():
        #...

    def time_interval():
        #....
    

