name: Lint and Test
on: [push]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming .
    - name: Lint
      working-directory: ${{ github.workspace }}
      run: |
        flake8
  test:
    name: Code Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest geopandas .
    - name: Test
      working-directory: ${{ github.workspace }}
      run: |
        pytest --verbose
