name: Lint and Test
on: [push, pull_request]

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make dev
      - name: Check code style
        working-directory: ${{ github.workspace }}
        run: |
          make lint
      - name: Runs unit tests
        working-directory: ${{ github.workspace }}
        run: |
          make test
