name: Lint and Test
on: [push]

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make env
    - name: Lint
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  test:
    name: Code Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.7
      uses: actions/setup-python@main
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make env
    - name: Test
      working-directory: ${{ github.workspace }}
      run: |
        make test
